let passwords = {
  "END": "END IS NEVER THE END",
  "END IS NEVER THE END":"<p>JR:alt scammed me outta my grist card</p><p>JR: actually let me back up</p><p>JR: you know how theres trickster versions of a lot of the chars?</p><p>JR: and some chars, like the closer</p><p>JR: just yeet themselves out of the universe</p><p>JR: to go cause problems on segundia?</p><p>JR: being in the maze all the time</p><p>JR: meant when alt got trickstered</p><p>JR: she could go *anywhere*</p><p>JR: closer could cuz she literally brought herself here through witch of breath bullshit</p><p>JR: so she could leave whenever she wants</p><p>JR: trickster or not</p><p>JR: its how she grabbed doc slaughter</p><p>JR: but alt</p><p>JR: trickster mode in homestuck is about superficially solving your problems</p><p>JR: trickster alt doesn't need to mimic anyone anymore</p><p>JR: she instead becomes a leprechaun that doens't exist</p><p>JR: and fucks with me just</p><p>JR: constantly</p><p>JR: now</p><p>JR: granted</p><p>JR: she wasn't ALWAYS loki</p><p>JR: obviously</p><p>JR: loki existed before she did</p><p>JR: before she existed even outside zampanio</p><p>JR: before we fed her to it</p><p>JR: but oxbow lakes</p><p>JR: you know</p><p>JR: we pinched her off and now she's always been loki</p><p>JR: speakng of oxbow lakes</p><p>JR: you know the radio audio logs?</p><p>JR: <a target='_blank' href ='http://www.farragofiction.com/AudioLogs/?passPhrase=a_river'>this one</a></p><p>JR: wait, no, <a target='_blank' href ='https://www.farragofiction.com/AudioLogs/?passPhrase=radio_a_river'>this one</a></p><p>JR:loki was always the host of the radio audio logs</p></p><p>JR:hence the constantly changing 'hosts'</p><p>JR:including one that was me but not me</p><p>JR:but yeah</p><p>JR:now</p><p>JR:in retrospect</p><p>JR:this is alt</p><p>JR:mimicking truth</p><p>JR:whle fucking with JR</p><p>JR:oh lol</p><p>JR:turns out you cant click links in this contenteditable mode</p><p>JR:well</p><p>JR:i tried to make this non-waste friendly</p><p>JR:but looks like you'll need to inspect the element after all</p><p>JR:to get to the audio logs</p></p><p>JR:but yeah</p><p>JR:alt was mimicking wodin when she made the knuckles sux blog</p><p>JR:but then real wodin discovered the site and started editing it</p><p>JR:it happens</p>",
  "TRUTH IS LAYERED":"<p>JR:Truth and Alt are such an odd couple</p><p>JR:they started out dating because of a video IC and i watched about house of jumpscares</p><p>JR:how i immediately started shipping the smaller maze inside the bigger maze</p><p>JR:the idea of alt wearing Truths face</p><p>JR:becoming a maze within a maze</p><p>JR:was fascinating to me</p><p>JR:if the physical space you are in is a person</p><p>JR:and you are *obligated* to copy any nearby person</p><p>JR:what do you even do</p><p>JR:Truth and Alt couldn't be more different if they tried at first glance.</p><p>JR:Truth is SO uncomfortable about falsehoods<p>JR:and alt literally scams people for a living</p><p>JR:but they both are so desperately clingy and lonely</p><p>JR: sure Truth SAYS it always speaks the truth</p><p>JR:but you SAW it in North didn't you?</p><p>JR:its not exctly against the idea of being tsundere at you for spite reasons</p><p>JR:even while begging you to stay</p><p>JR:its like if that riddle about the guard that always lies and the guard that always tells the truth had an asterisk and it turned out they both lied if they thought you were going to leave</p><p>JR:Truth just wants you to stay and alt just wants you to stay and they want each OTHER to stay and they're willing to make it work</p><p>JR:whatever it takes</p><p>JR:gratned its not exactly healthy</p><p>JR: to be literally trapped together and desperate for attention</p><p>JR:but neither of them would be better off alone</p><p>JR:so what can you do</p>",
  "TRUTH": "TRUTH IS LAYERED",
  "FARRAGNAROK":"https://farragofiction.com/LOHAE",
  "WHAT":"do you traverse mazes clockwise?",
  "GO":"GO TO ZEUS TO PLEAD FOR HER LIFE",
  "ECHIDNA":"http://www.farragofiction.com/AudioLogs/?passPhrase=echidna_laugh",
  "GROSS":"echidnalaugh not echidna_laugh",
  "TOXIC":"<p>JR: truth and alt might not have the healthiest relationship</p><p>JR: but it makes them happier than they've ever been</p><p>JR:</p><p>JR:and one of the things i'm exploring with my branch of zampanio is</p><p>JR:this idea that</p><p>JR:you can be happy</p><p>JR:even if you're not perfect</p><p>JR:even if you're not your ideal self</p><p>JR:even if you feel like a monster</p><p>JR:you can find happiness</p><p>JR:and you can find a path towards becoming a better person</p><p>JR: if these literal monsters can</p><p>JR:so can you</p><p>JR:and yes</p><p>JR:maybe its not healthy to cling in desperation</p><p>JR:maybe theres better ways</p><p>JR:there ARE better ways</p><p>JR:but</p><p>JR:how do you even BEGIN to learn those better ways without practice</p><p>JR:are truth and alt supposed to live in a monestrary </p><p>JR:in silence</p><p>JR:meditating on how to be a better person?</p><p>JR:are you?</p><p>JR:absolutely dont force someone to be around you</p><p>JR:if they want to leave</p><p>JR:but you don't have to force them to leave you either</p><p>JR:if they don't want to</p><p>JR:truth and alt are happy</p><p>JR:and neither feels the other is hurting them</p><p>JR:even if they both might cling too tightly</p><p>JR:even if how they act might hurt someone else</p><p>JR:its okay because they both say it is",

  "GO TO ZEUS TO PLEAD FOR HER LIFE":"http://gopher.floodgap.com/gopher/gw?gopher://farragofiction.com:70/1/",
  "DO YOU TRAVERSE MAZES CLOCKWISE":"http://www.farragofiction.com/ZampanioSimSouthSouth/",
  "NOT":"<p>JR:alt is not what she is</p><p>JR:but also isn't anything else</p><p>JR:she can become anything</p><p>JR:as far as i can tell she HAS to become anything</p><p>JR:loneliness is literally fatal for her</p><p>JR:she needs to be around people</p><p>JR:to wear their faces</p><p>JR:'look at me' she says, 'i'm just like you'</p><p>JR:ofc, i don't know</p><p>JR:not for sure</p><p>JR:she's ICs</p><p>JR:a lot of them are actually</p><p>JR:but a lot i've got the feel of</p><p>JR:but alt and the flower chick shes the copy of</p><p>JR:don't take up as much space in my brain</p><p>JR:or was it that alt and flower chick are copies of the same third person</p><p>JR:doesn't really matter</p>",
  "SEXY SINGLES":"<p>JR: you know about the porn bot apocalypse, right?</p><p>JR: on tumblr I mean</p><p>JR: all those sexy singles just dying to share sus links with you</p><p>JR:i DID have fun making this, thank you for asking </p><p>JR: I've been wanting to make another alt focused site for a while.</p><p>JR: you DID find the Truth About Alt, right?</p><p>JR: poor girl lost too many people</p><p>JR:like permanently lost<p>JR:lone survivor kinda deal</p><p>JR:multiple times</p><p>JR:and well</p><p>JR: if no one can die in Truth's Maze</p><p>JR: thats a small price to pay</p><p>JR:isn't it?</p><p>JR:to never lose anyone again</p><p>JR:so she (and well, Truth, obviously) are the only NonNamed character who will never show up in the Universe.<p>JR:truths maze is beyond it</p><p>JR:on the moon</p><p>JR:if you want a metaphor</p><p>JR:where an entire universe can be a single planet</p><p>JR:POINT is</p><p>JR:alt doesnt leave the maze</p><p>JR:but its not just Truths maze</p><p>JR:its wandas, too</p><p>JR: so obviously its got wifi</p><p>JR:alt has run quite a scam empire from inside the maze</p><p>JR:really all she wants to do is make friends</p><p>JR:the quotidians like her a lot</p><p>JR:help her find friends as best they can</p><p>JR:theyre a lil confused, but they got the spirit</p><p>JR:everybody likes making friends with sexy singles</p>"
}